version: '3.8'

services:

  # gradio:
  #   build: ./
  #   container_name: gradio
  #   env_file:
  #     - .env
  #   ports:
  #     - ${GRADIO_SERVER_PORT}:${GRADIO_SERVER_PORT}
  #   depends_on:
  #     - qdrant
  #     - mongo
  #     - ollama

  app:
    build: ./
    container_name: app
    # command: fastapi run app/src/app/main.py --port ${FASTAPI_PORT}
    env_file:
      - .env
    ports:
      - ${FASTAPI_PORT}:${FASTAPI_PORT}
    depends_on:
      - qdrant
      - mongo
      - ollama

  ollama:
    image: ollama/ollama:latest
    container_name: ollama
    restart: always
    tty: true
    environment:
      - OLLAMA_LLM=${OLLAMA_LLM}
    entrypoint: ["/usr/bin/bash", "/entrypoint.sh"]
    ports:
        - ${OLLAMA_PORT}:${OLLAMA_PORT}
    volumes:
        - ollama:/root/.ollama:/root/.ollama
        - ./entrypoint.sh:/entrypoint.sh
    deploy:
      resources:
        reservations:
          devices:
          - driver: nvidia
            capabilities: ["gpu"]
            count: all
   

  qdrant:
    image: qdrant/qdrant:latest
    container_name: qdrant
    restart: always
    tty: true
    ports:
      - ${QDRANT_PORT}:${QDRANT_PORT}
    volumes:
      - qdrant_storage:/qdrant/storage



  mongo:
    image: mongo:latest
    container_name: mongo
    restart: always
    tty: true
    ports:
      - ${MONGO_PORT}:${MONGO_PORT}
    volumes:
      - mongo_data_db:/data/db


  mongo-express:
    image: mongo-express:latest
    restart: always
    tty: true
    ports:
      - ${MONGOEXPRESS_PORT}:${MONGOEXPRESS_PORT}
    environment:
      - ME_CONFIG_MONGODB_URL=mongodb://${MONGO_HOST}:${MONGO_PORT}/
      - ME_CONFIG_BASICAUTH=false
    depends_on: 
      - mongo

volumes:
  qdrant_storage:
    driver: local
  mongo_data_db:
    driver: local
  ollama:
    driver: local

