FROM python:3.9-slim

RUN pip install  "poetry==1.7.1"

RUN pip install poetry==1.7.1

ENV POETRY_NO_INTERACTION=1 \
    POETRY_VIRTUALENVS_IN_PROJECT=1 \
    POETRY_VIRTUALENVS_CREATE=1 \
    POETRY_CACHE_DIR=/tmp/poetry_cache

ENV API_PORT=${API_PORT}

WORKDIR /app

RUN touch README.md
COPY pyproject.toml poetry.lock ./
RUN poetry install --no-root --only ui
RUN rm -rf $POETRY_CACHE_DIR

RUN mkdir src
COPY src/__init__.py src/settings.py ./src/

COPY data/ ./data/
COPY src/rag/ ./src/rag/
COPY src/api/ ./src/api/

# CMD ["poetry", "run", "fastapi", "run", "src/api/main.py", "--port", ${API_PORT}]
